import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import * as fs from 'fs';
import Link from 'next/link'
import Image from 'next/image'

export default function Home(props) {
  const [blogs, setBlogs] = useState(props.allBlogs);
  return <>
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<main className={styles.main}>
        <h1 className={styles.title}>
          <span>HUNTING CODER</span>
        </h1>
        <div className={styles.images}>
          <div className={styles.wrapDiv}>
          <Image src="/homeimg.jpg" width={500} height={350} alt="" className={styles.Img1}/>
          <Image src="/homeimg2.jpg" width={500} height={350} alt="" className={styles.Img2}/>
          <Image src="/homeimg3.avif" width={500} height={350} alt="" className={styles.Img3}/>
          </div>
      </div>
<h1 className={styles.mainH1}>Popular Blogs</h1>
  {blogs.map((blogitem)=>{
        return  <>
        <div className={styles.blogItem} key={blogitem.title}>
        <Link passHref href={`/blogpost/${blogitem.slug}`}>
        <h2>{blogitem.title}</h2>     
         </Link>
        <p className={styles.blogItemP}>{blogitem.metadesc.substr(0, 140)}</p>
        <button type="submit" className={styles.button}><Link passHref href={`/blogpost/${blogitem.slug}`}>READ MORE</Link></button>
      </div>
      </>
      })}
  </main>
  </div>
  </>
}

export async function getStaticProps(context) {
  let data = await fs.promises.readdir('blogdata');
  let allCount = data.length;
  let myfile;
  let allBlogs = [];
  for (let index = 0; index < 2; index++) {
    const item = data[index];
    myfile = await fs.promises.readFile(('blogdata/' + item), 'utf-8');
    allBlogs.push(JSON.parse(myfile))
  }
  return {
    props: { allBlogs, allCount },
  }
}
